
name: Linux, build and test

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build configuration"
        required: true
        default: "Release"

env:
  BUILD_TYPE: Release
  BUILD_DIRECTORY: build
  INSTALL_DIRECTORY: dist
  CERTIFICATE_DIRECTORY: cert
  APP_NAME: market-bridge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update  
        sudo apt-get install -y libssl-dev

    - name: Configure CMake
      run: cmake -S. -B ${{github.workspace}}/${{env.BUILD_DIRECTORY}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIRECTORY}} --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/${{env.BUILD_DIRECTORY}}/tests
      run: ctest -V

    - name: Install
      run: cmake --install ${{github.workspace}}/${{env.BUILD_DIRECTORY}} --prefix ${{github.workspace}}/${{env.INSTALL_DIRECTORY}}

    - name: Check OpenSSL
      run: |
        which openssl
        openssl version

    - name: Generate self-signed HTTPS test certificates
      working-directory: ${{github.workspace}}/${{env.INSTALL_DIRECTORY}}
      run: |
        mkdir ${{env.INSTALL_DIRECTORY}}
        cd ${{env.INSTALL_DIRECTORY}}
        openssl req -x509 -newkey rsa:2048 -days 1 -keyout server.key -out server.crt -nodes -subj "/CN=localhost"
        ls -l .

    - name: Run ${{env.APP_NAME}}
      working-directory: ${{github.workspace}}/${{env.INSTALL_DIRECTORY}}
      run: bin/${{env.APP_NAME}} --help
      
